# These are supported funding model platforms

github: [babel] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: code_cloud_all # Replace with a single Patreon username)
ko_fi: coderbasket
custom: https://gitcoin.co/grants/2906/babel-compiler-for-next-generation-javascript # Replace with a single custom sponsorship URL

